

<!--REINTEGRATION DES _POST DANS LES VARIABLES _SESSION-->
<?php 
$_SESSION['dividendes_p4'] = $_POST['dividendes_p4'];
$_SESSION['montant_p4'] = $_POST['montant_p4'];
$_SESSION['equipement1achat_p4'] = $_POST['equipement1achat_p4'];
$_SESSION['equipement2achat_p4'] = $_POST['equipement2achat_p4'];
$_SESSION['equipement3achat_p4'] = $_POST['equipement3achat_p4'];
$_SESSION['budgetmaintenance_p4'] = $_POST['budgetmaintenance_p4'];
$_SESSION['embaucheouvrier_p4'] = $_POST['embaucheouvrier_p4'];
$_SESSION['licenciementouvrier_p4'] = $_POST['licenciementouvrier_p4'];
$_SESSION['indiceouvrier_p4'] = $_POST['indiceouvrier_p4'];
$_SESSION['budgetsocial_p4']  = $_POST['budgetsocial_p4'];
/* $_SESSION['communicationglobale_p4']  = $_POST['communicationglobale_p4'];
$_SESSION['polyvalents_p4']  = $_POST['polyvalents_p4']; */
$_SESSION['product1licence_p4']  = $_POST['product1licence_p4'];
$_SESSION['product1production_p4']  = $_POST['product1production_p4'];
$_SESSION['product1qualite_p4']  = $_POST['product1qualite_p4'];
$_SESSION['product1soustraitance_p4'] = $_POST['product1soustraitance_p4'];
$_SESSION['product1pdv_p4']  = $_POST['product1pdv_p4'];
$_SESSION['product1communication_p4'] = $_POST['product1communication_p4'];
$_SESSION['product1commerciaux_p4'] = $_POST['product1commerciaux_p4'];
$_SESSION['product1indicefdv_p4'] = $_POST['product1indicefdv_p4'];
$_SESSION['product1icreditclient_p4'] = $_POST['product1icreditclient_p4'];
$_SESSION['product2licence_p4']  = $_POST['product2licence_p4'];
$_SESSION['product2production_p4']  = $_POST['product2production_p4'];
$_SESSION['product2qualite_p4']  = $_POST['product2qualite_p4'];
$_SESSION['product2soustraitance_p4'] = $_POST['product2soustraitance_p4'];
$_SESSION['product2pdv_p4']  = $_POST['product2pdv_p4'];
$_SESSION['product2communication_p4'] = $_POST['product2communication_p4'];
$_SESSION['product2commerciaux_p4'] = $_POST['product2commerciaux_p4'];
$_SESSION['product2indicefdv_p4'] = $_POST['product2indicefdv_p4'];
$_SESSION['product2icreditclient_p4'] = $_POST['product2icreditclient_p4'];
$_SESSION['product3licence_p4']  = $_POST['product3licence_p4'];
$_SESSION['product3production_p4']  = $_POST['product3production_p4'];
$_SESSION['product3qualite_p4']  = $_POST['product3qualite_p4'];
$_SESSION['product3soustraitance_p4'] = $_POST['product3soustraitance_p4'];
$_SESSION['product3pdv_p4']  = $_POST['product3pdv_p4'];
$_SESSION['product3communication_p4'] = $_POST['product3communication_p4'];
$_SESSION['product3commerciaux_p4'] = $_POST['product3commerciaux_p4'];
$_SESSION['product3indicefdv_p4'] = $_POST['product3indicefdv_p4'];
$_SESSION['product3icreditclient_p4'] = $_POST['product3icreditclient_p4'];
$_SESSION['product4licence_p4']  = $_POST['product4licence_p4'];
$_SESSION['product4production_p4']  = $_POST['product4production_p4'];
$_SESSION['product4qualite_p4']  = $_POST['product4qualite_p4'];
$_SESSION['product4soustraitance_p4'] = $_POST['product4soustraitance_p4'];
$_SESSION['product4pdv_p4']  = $_POST['product4pdv_p4'];
$_SESSION['product4communication_p4'] = $_POST['product4communication_p4'];
$_SESSION['product4commerciaux_p4'] = $_POST['product4commerciaux_p4'];
$_SESSION['product4indicefdv_p4'] = $_POST['product4indicefdv_p4'];
$_SESSION['product4icreditclient_p4'] = $_POST['product4icreditclient_p4'];
$_SESSION['product5licence_p4']  = $_POST['product5licence_p4'];
$_SESSION['product5production_p4']  = $_POST['product5production_p4'];
$_SESSION['product5qualite_p4']  = $_POST['product5qualite_p4'];
$_SESSION['product5soustraitance_p4'] = $_POST['product5soustraitance_p4'];
$_SESSION['product5pdv_p4']  = $_POST['product5pdv_p4'];
$_SESSION['product5communication_p4'] = $_POST['product5communication_p4'];
$_SESSION['product5commerciaux_p4'] = $_POST['product5commerciaux_p4'];
$_SESSION['product5indicefdv_p4'] = $_POST['product5indicefdv_p4'];
$_SESSION['product5icreditclient_p4'] = $_POST['product5icreditclient_p4'];
?>
