

<!--REINTEGRATION DES _POST DANS LES VARIABLES _SESSION-->
<?php 


if (isset($_POST['item_dividendes_p1']))		{ $_SESSION['item_dividendes_p1']	= $_POST['item_dividendes_p1']; }		else {    $_SESSION['item_dividendes_p1'] = 'non' ; }
if (isset($_POST['item_dividendes_p2']))		{ $_SESSION['item_dividendes_p2']	= $_POST['item_dividendes_p2']; }		else {    $_SESSION['item_dividendes_p2'] = 'non' ; }
if (isset($_POST['item_dividendes_p3']))		{ $_SESSION['item_dividendes_p3']	= $_POST['item_dividendes_p3']; }		else {    $_SESSION['item_dividendes_p3'] = 'non' ; }
if (isset($_POST['item_dividendes_p4']))		{ $_SESSION['item_dividendes_p4']	= $_POST['item_dividendes_p4']; }		else {    $_SESSION['item_dividendes_p4'] = 'non' ; }
if (isset($_POST['item_dividendes_p5']))		{ $_SESSION['item_dividendes_p5']	= $_POST['item_dividendes_p5']; }		else {    $_SESSION['item_dividendes_p5'] = 'non' ; }
if (isset($_POST['item_dividendes_p6']))		{ $_SESSION['item_dividendes_p6']	= $_POST['item_dividendes_p6']; }		else {    $_SESSION['item_dividendes_p6'] = 'non' ; }
if (isset($_POST['item_emprunt_p1']))		{ $_SESSION['item_emprunt_p1']	= $_POST['item_emprunt_p1']; }		else {    $_SESSION['item_emprunt_p1'] = 'non' ; }
if (isset($_POST['item_emprunt_p2']))		{ $_SESSION['item_emprunt_p2']	= $_POST['item_emprunt_p2']; }		else {    $_SESSION['item_emprunt_p2'] = 'non' ; }
if (isset($_POST['item_emprunt_p3']))		{ $_SESSION['item_emprunt_p3']	= $_POST['item_emprunt_p3']; }		else {    $_SESSION['item_emprunt_p3'] = 'non' ; }
if (isset($_POST['item_emprunt_p4']))		{ $_SESSION['item_emprunt_p4']	= $_POST['item_emprunt_p4']; }		else {    $_SESSION['item_emprunt_p4'] = 'non' ; }
if (isset($_POST['item_emprunt_p5']))		{ $_SESSION['item_emprunt_p5']	= $_POST['item_emprunt_p5']; }		else {    $_SESSION['item_emprunt_p5'] = 'non' ; }
if (isset($_POST['item_emprunt_p6']))		{ $_SESSION['item_emprunt_p6']	= $_POST['item_emprunt_p6']; }		else {    $_SESSION['item_emprunt_p6'] = 'non' ; }

if (isset($_POST['item_machine1_p1']))		{ $_SESSION['item_machine1_p1']	= $_POST['item_machine1_p1']; }		else {    $_SESSION['item_machine1_p1'] = 'non' ; }
if (isset($_POST['item_machine1_p2']))		{ $_SESSION['item_machine1_p2']	= $_POST['item_machine1_p2']; }		else {    $_SESSION['item_machine1_p2'] = 'non' ; }
if (isset($_POST['item_machine1_p3']))		{ $_SESSION['item_machine1_p3']	= $_POST['item_machine1_p3']; }		else {    $_SESSION['item_machine1_p3'] = 'non' ; }
if (isset($_POST['item_machine1_p4']))		{ $_SESSION['item_machine1_p4']	= $_POST['item_machine1_p4']; }		else {    $_SESSION['item_machine1_p4'] = 'non' ; }
if (isset($_POST['item_machine1_p5']))		{ $_SESSION['item_machine1_p5']	= $_POST['item_machine1_p5']; }		else {    $_SESSION['item_machine1_p5'] = 'non' ; }
if (isset($_POST['item_machine1_p6']))		{ $_SESSION['item_machine1_p6']	= $_POST['item_machine1_p6']; }		else {    $_SESSION['item_machine1_p6'] = 'non' ; }
if (isset($_POST['item_machine2_p1']))		{ $_SESSION['item_machine2_p1']	= $_POST['item_machine2_p1']; }		else {    $_SESSION['item_machine2_p1'] = 'non' ; }
if (isset($_POST['item_machine2_p2']))		{ $_SESSION['item_machine2_p2']	= $_POST['item_machine2_p2']; }		else {    $_SESSION['item_machine2_p2'] = 'non' ; }
if (isset($_POST['item_machine2_p3']))		{ $_SESSION['item_machine2_p3']	= $_POST['item_machine2_p3']; }		else {    $_SESSION['item_machine2_p3'] = 'non' ; }
if (isset($_POST['item_machine2_p4']))		{ $_SESSION['item_machine2_p4']	= $_POST['item_machine2_p4']; }		else {    $_SESSION['item_machine2_p4'] = 'non' ; }
if (isset($_POST['item_machine2_p5']))		{ $_SESSION['item_machine2_p5']	= $_POST['item_machine2_p5']; }		else {    $_SESSION['item_machine2_p5'] = 'non' ; }
if (isset($_POST['item_machine2_p6']))		{ $_SESSION['item_machine2_p6']	= $_POST['item_machine2_p6']; }		else {    $_SESSION['item_machine2_p6'] = 'non' ; }
if (isset($_POST['item_machine3_p1']))		{ $_SESSION['item_machine3_p1']	= $_POST['item_machine3_p1']; }		else {    $_SESSION['item_machine3_p1'] = 'non' ; }
if (isset($_POST['item_machine3_p2']))		{ $_SESSION['item_machine3_p2']	= $_POST['item_machine3_p2']; }		else {    $_SESSION['item_machine3_p2'] = 'non' ; }
if (isset($_POST['item_machine3_p3']))		{ $_SESSION['item_machine3_p3']	= $_POST['item_machine3_p3']; }		else {    $_SESSION['item_machine3_p3'] = 'non' ; }
if (isset($_POST['item_machine3_p4']))		{ $_SESSION['item_machine3_p4']	= $_POST['item_machine3_p4']; }		else {    $_SESSION['item_machine3_p4'] = 'non' ; }
if (isset($_POST['item_machine3_p5']))		{ $_SESSION['item_machine3_p5']	= $_POST['item_machine3_p5']; }		else {    $_SESSION['item_machine3_p5'] = 'non' ; }
if (isset($_POST['item_machine3_p6']))		{ $_SESSION['item_machine3_p6']	= $_POST['item_machine3_p6']; }		else {    $_SESSION['item_machine3_p6'] = 'non' ; }
if (isset($_POST['item_budgetmaintenance_p1']))	{ $_SESSION['item_budgetmaintenance_p1']	= $_POST['item_budgetmaintenance_p1']; }	else {    $_SESSION['item_budgetmaintenance_p1'] = 'non' ; }
if (isset($_POST['item_budgetmaintenance_p2']))	{ $_SESSION['item_budgetmaintenance_p2']	= $_POST['item_budgetmaintenance_p2']; }	else {    $_SESSION['item_budgetmaintenance_p2'] = 'non' ; }
if (isset($_POST['item_budgetmaintenance_p3']))	{ $_SESSION['item_budgetmaintenance_p3']	= $_POST['item_budgetmaintenance_p3']; }	else {    $_SESSION['item_budgetmaintenance_p3'] = 'non' ; }
if (isset($_POST['item_budgetmaintenance_p4']))	{ $_SESSION['item_budgetmaintenance_p4']	= $_POST['item_budgetmaintenance_p4']; }	else {    $_SESSION['item_budgetmaintenance_p4'] = 'non' ; }
if (isset($_POST['item_budgetmaintenance_p5']))	{ $_SESSION['item_budgetmaintenance_p5']	= $_POST['item_budgetmaintenance_p5']; }	else {    $_SESSION['item_budgetmaintenance_p5'] = 'non' ; }
if (isset($_POST['item_budgetmaintenance_p6']))	{ $_SESSION['item_budgetmaintenance_p6']	= $_POST['item_budgetmaintenance_p6']; }	else {    $_SESSION['item_budgetmaintenance_p6'] = 'non' ; }

if (isset($_POST['item_recrutementouvrier_p1'])) { $_SESSION['item_recrutementouvrier_p1']	= $_POST['item_recrutementouvrier_p1']; }	else {    $_SESSION['item_recrutementouvrier_p1'] = 'non' ; }
if (isset($_POST['item_recrutementouvrier_p2'])) { $_SESSION['item_recrutementouvrier_p2']	= $_POST['item_recrutementouvrier_p2']; }	else {    $_SESSION['item_recrutementouvrier_p2'] = 'non' ; }
if (isset($_POST['item_recrutementouvrier_p3'])) { $_SESSION['item_recrutementouvrier_p3']	= $_POST['item_recrutementouvrier_p3']; }	else {    $_SESSION['item_recrutementouvrier_p3'] = 'non' ; }
if (isset($_POST['item_recrutementouvrier_p4'])) { $_SESSION['item_recrutementouvrier_p4']	= $_POST['item_recrutementouvrier_p4']; }	else {    $_SESSION['item_recrutementouvrier_p4'] = 'non' ; }
if (isset($_POST['item_recrutementouvrier_p5'])) { $_SESSION['item_recrutementouvrier_p5']	= $_POST['item_recrutementouvrier_p5']; }	else {    $_SESSION['item_recrutementouvrier_p5'] = 'non' ; }
if (isset($_POST['item_recrutementouvrier_p6'])) { $_SESSION['item_recrutementouvrier_p6']	= $_POST['item_recrutementouvrier_p6']; }	else {    $_SESSION['item_recrutementouvrier_p6'] = 'non' ; }
if (isset($_POST['item_licenciementouvrier_p1'])) { $_SESSION['item_licenciementouvrier_p1'] = $_POST['item_licenciementouvrier_p1']; }	else {    $_SESSION['item_licenciementouvrier_p1'] = 'non' ; }
if (isset($_POST['item_licenciementouvrier_p2'])) { $_SESSION['item_licenciementouvrier_p2'] = $_POST['item_licenciementouvrier_p2']; }	else {    $_SESSION['item_licenciementouvrier_p2'] = 'non' ; }
if (isset($_POST['item_licenciementouvrier_p3'])) { $_SESSION['item_licenciementouvrier_p3'] = $_POST['item_licenciementouvrier_p3']; }	else {    $_SESSION['item_licenciementouvrier_p3'] = 'non' ; }
if (isset($_POST['item_licenciementouvrier_p4'])) { $_SESSION['item_licenciementouvrier_p4'] = $_POST['item_licenciementouvrier_p4']; }	else {    $_SESSION['item_licenciementouvrier_p4'] = 'non' ; }
if (isset($_POST['item_licenciementouvrier_p5'])) { $_SESSION['item_licenciementouvrier_p5'] = $_POST['item_licenciementouvrier_p5']; }	else {    $_SESSION['item_licenciementouvrier_p5'] = 'non' ; }
if (isset($_POST['item_licenciementouvrier_p6'])) { $_SESSION['item_licenciementouvrier_p6'] = $_POST['item_licenciementouvrier_p6']; }	else {    $_SESSION['item_licenciementouvrier_p6'] = 'non' ; }
if (isset($_POST['item_indiceouvrier_p1']))		{ $_SESSION['item_indiceouvrier_p1']	= $_POST['item_indiceouvrier_p1']; }		else {    $_SESSION['item_indiceouvrier_p1'] = 'non' ; }
if (isset($_POST['item_indiceouvrier_p2']))		{ $_SESSION['item_indiceouvrier_p2']	= $_POST['item_indiceouvrier_p2']; }		else {    $_SESSION['item_indiceouvrier_p2'] = 'non' ; }
if (isset($_POST['item_indiceouvrier_p3']))		{ $_SESSION['item_indiceouvrier_p3']	= $_POST['item_indiceouvrier_p3']; }		else {    $_SESSION['item_indiceouvrier_p3'] = 'non' ; }
if (isset($_POST['item_indiceouvrier_p4']))		{ $_SESSION['item_indiceouvrier_p4']	= $_POST['item_indiceouvrier_p4']; }		else {    $_SESSION['item_indiceouvrier_p4'] = 'non' ; }
if (isset($_POST['item_indiceouvrier_p5']))		{ $_SESSION['item_indiceouvrier_p5']	= $_POST['item_indiceouvrier_p5']; }		else {    $_SESSION['item_indiceouvrier_p5'] = 'non' ; }
if (isset($_POST['item_indiceouvrier_p6']))		{ $_SESSION['item_indiceouvrier_p6']	= $_POST['item_indiceouvrier_p6']; }		else {    $_SESSION['item_indiceouvrier_p6'] = 'non' ; }
if (isset($_POST['item_budgetsocial_p1']))		{ $_SESSION['item_budgetsocial_p1']	= $_POST['item_budgetsocial_p1']; }		else {    $_SESSION['item_budgetsocial_p1'] = 'non' ; }
if (isset($_POST['item_budgetsocial_p2']))		{ $_SESSION['item_budgetsocial_p2']	= $_POST['item_budgetsocial_p2']; }		else {    $_SESSION['item_budgetsocial_p2'] = 'non' ; }
if (isset($_POST['item_budgetsocial_p3']))		{ $_SESSION['item_budgetsocial_p3']	= $_POST['item_budgetsocial_p3']; }		else {    $_SESSION['item_budgetsocial_p3'] = 'non' ; }
if (isset($_POST['item_budgetsocial_p4']))		{ $_SESSION['item_budgetsocial_p4']	= $_POST['item_budgetsocial_p4']; }		else {    $_SESSION['item_budgetsocial_p4'] = 'non' ; }
if (isset($_POST['item_budgetsocial_p5']))		{ $_SESSION['item_budgetsocial_p5']	= $_POST['item_budgetsocial_p5']; }		else {    $_SESSION['item_budgetsocial_p5'] = 'non' ; }
if (isset($_POST['item_budgetsocial_p6']))		{ $_SESSION['item_budgetsocial_p6']	= $_POST['item_budgetsocial_p6']; }		else {    $_SESSION['item_budgetsocial_p6'] = 'non' ; }






if (isset($_POST['item_product1_licence_p1']))		{ $_SESSION['item_product1_licence_p1']	= $_POST['item_product1_licence_p1']; }		else {    $_SESSION['item_product1_licence_p1'] = 'non' ; }
if (isset($_POST['item_product1_licence_p2']))		{ $_SESSION['item_product1_licence_p2']	= $_POST['item_product1_licence_p2']; }		else {    $_SESSION['item_product1_licence_p2'] = 'non' ; }
if (isset($_POST['item_product1_licence_p3']))		{ $_SESSION['item_product1_licence_p3']	= $_POST['item_product1_licence_p3']; }		else {    $_SESSION['item_product1_licence_p3'] = 'non' ; }
if (isset($_POST['item_product1_licence_p4']))		{ $_SESSION['item_product1_licence_p4']	= $_POST['item_product1_licence_p4']; }		else {    $_SESSION['item_product1_licence_p4'] = 'non' ; }
if (isset($_POST['item_product1_licence_p5']))		{ $_SESSION['item_product1_licence_p5']	= $_POST['item_product1_licence_p5']; }		else {    $_SESSION['item_product1_licence_p5'] = 'non' ; }
if (isset($_POST['item_product1_licence_p6']))		{ $_SESSION['item_product1_licence_p6']	= $_POST['item_product1_licence_p6']; }		else {    $_SESSION['item_product1_licence_p6'] = 'non' ; }
if (isset($_POST['item_product1_production_p1'])) { $_SESSION['item_product1_production_p1']	= $_POST['item_product1_production_p1']; } else { $_SESSION['item_product1_production_p1'] = 'non' ; }
if (isset($_POST['item_product1_production_p2'])) { $_SESSION['item_product1_production_p2']	= $_POST['item_product1_production_p2']; } else { $_SESSION['item_product1_production_p2'] = 'non' ; }
if (isset($_POST['item_product1_production_p3'])) { $_SESSION['item_product1_production_p3']	= $_POST['item_product1_production_p3']; } else { $_SESSION['item_product1_production_p3'] = 'non' ; }
if (isset($_POST['item_product1_production_p4'])) { $_SESSION['item_product1_production_p4']	= $_POST['item_product1_production_p4']; } else { $_SESSION['item_product1_production_p4'] = 'non' ; }
if (isset($_POST['item_product1_production_p5'])) { $_SESSION['item_product1_production_p5']	= $_POST['item_product1_production_p5']; } else { $_SESSION['item_product1_production_p5'] = 'non' ; }
if (isset($_POST['item_product1_production_p6'])) { $_SESSION['item_product1_production_p6']	= $_POST['item_product1_production_p6']; } else { $_SESSION['item_product1_production_p6'] = 'non' ; }
if (isset($_POST['item_product1_qualite_p1']))		{ $_SESSION['item_product1_qualite_p1']	= $_POST['item_product1_qualite_p1']; }		else {    $_SESSION['item_product1_qualite_p1'] = 'non' ; }
if (isset($_POST['item_product1_qualite_p2']))		{ $_SESSION['item_product1_qualite_p2']	= $_POST['item_product1_qualite_p2']; }		else {    $_SESSION['item_product1_qualite_p2'] = 'non' ; }
if (isset($_POST['item_product1_qualite_p3']))		{ $_SESSION['item_product1_qualite_p3']	= $_POST['item_product1_qualite_p3']; }		else {    $_SESSION['item_product1_qualite_p3'] = 'non' ; }
if (isset($_POST['item_product1_qualite_p4']))		{ $_SESSION['item_product1_qualite_p4']	= $_POST['item_product1_qualite_p4']; }		else {    $_SESSION['item_product1_qualite_p4'] = 'non' ; }
if (isset($_POST['item_product1_qualite_p5']))		{ $_SESSION['item_product1_qualite_p5']	= $_POST['item_product1_qualite_p5']; }		else {    $_SESSION['item_product1_qualite_p5'] = 'non' ; }
if (isset($_POST['item_product1_qualite_p6']))		{ $_SESSION['item_product1_qualite_p6']	= $_POST['item_product1_qualite_p6']; }		else {    $_SESSION['item_product1_qualite_p6'] = 'non' ; }
if (isset($_POST['item_product1_soustraitance_p1'])) { $_SESSION['item_product1_soustraitance_p1'] = $_POST['item_product1_soustraitance_p1']; } else { $_SESSION['item_product1_soustraitance_p1'] = 'non' ; }
if (isset($_POST['item_product1_soustraitance_p2'])) { $_SESSION['item_product1_soustraitance_p2'] = $_POST['item_product1_soustraitance_p2']; } else { $_SESSION['item_product1_soustraitance_p2'] = 'non' ; }
if (isset($_POST['item_product1_soustraitance_p3'])) { $_SESSION['item_product1_soustraitance_p3'] = $_POST['item_product1_soustraitance_p3']; } else { $_SESSION['item_product1_soustraitance_p3'] = 'non' ; }
if (isset($_POST['item_product1_soustraitance_p4'])) { $_SESSION['item_product1_soustraitance_p4'] = $_POST['item_product1_soustraitance_p4']; } else { $_SESSION['item_product1_soustraitance_p4'] = 'non' ; }
if (isset($_POST['item_product1_soustraitance_p5'])) { $_SESSION['item_product1_soustraitance_p5'] = $_POST['item_product1_soustraitance_p5']; } else { $_SESSION['item_product1_soustraitance_p5'] = 'non' ; }
if (isset($_POST['item_product1_soustraitance_p6'])) { $_SESSION['item_product1_soustraitance_p6'] = $_POST['item_product1_soustraitance_p6']; } else { $_SESSION['item_product1_soustraitance_p6'] = 'non' ; }
if (isset($_POST['item_product1_budgetcom_p1']))		{ $_SESSION['item_product1_budgetcom_p1']	= $_POST['item_product1_budgetcom_p1']; }		else {    $_SESSION['item_product1_budgetcom_p1'] = 'non' ; }
if (isset($_POST['item_product1_budgetcom_p2']))		{ $_SESSION['item_product1_budgetcom_p2']	= $_POST['item_product1_budgetcom_p2']; }		else {    $_SESSION['item_product1_budgetcom_p2'] = 'non' ; }
if (isset($_POST['item_product1_budgetcom_p3']))		{ $_SESSION['item_product1_budgetcom_p3']	= $_POST['item_product1_budgetcom_p3']; }		else {    $_SESSION['item_product1_budgetcom_p3'] = 'non' ; }
if (isset($_POST['item_product1_budgetcom_p4']))		{ $_SESSION['item_product1_budgetcom_p4']	= $_POST['item_product1_budgetcom_p4']; }		else {    $_SESSION['item_product1_budgetcom_p4'] = 'non' ; }
if (isset($_POST['item_product1_budgetcom_p5']))		{ $_SESSION['item_product1_budgetcom_p5']	= $_POST['item_product1_budgetcom_p5']; }		else {    $_SESSION['item_product1_budgetcom_p5'] = 'non' ; }
if (isset($_POST['item_product1_budgetcom_p6']))		{ $_SESSION['item_product1_budgetcom_p6']	= $_POST['item_product1_budgetcom_p6']; }		else {    $_SESSION['item_product1_budgetcom_p6'] = 'non' ; }
if (isset($_POST['item_product1_commerciaux_p1']))		{ $_SESSION['item_product1_commerciaux_p1']	= $_POST['item_product1_commerciaux_p1']; }		else {    $_SESSION['item_product1_commerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product1_commerciaux_p2']))		{ $_SESSION['item_product1_commerciaux_p2']	= $_POST['item_product1_commerciaux_p2']; }		else {    $_SESSION['item_product1_commerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product1_commerciaux_p3']))		{ $_SESSION['item_product1_commerciaux_p3']	= $_POST['item_product1_commerciaux_p3']; }		else {    $_SESSION['item_product1_commerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product1_commerciaux_p4']))		{ $_SESSION['item_product1_commerciaux_p4']	= $_POST['item_product1_commerciaux_p4']; }		else {    $_SESSION['item_product1_commerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product1_commerciaux_p5']))		{ $_SESSION['item_product1_commerciaux_p5']	= $_POST['item_product1_commerciaux_p5']; }		else {    $_SESSION['item_product1_commerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product1_commerciaux_p6']))		{ $_SESSION['item_product1_commerciaux_p6']	= $_POST['item_product1_commerciaux_p6']; }		else {    $_SESSION['item_product1_commerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product1_indicecommerciaux_p1']))		{ $_SESSION['item_product1_indicecommerciaux_p1']	= $_POST['item_product1_indicecommerciaux_p1']; }		else {    $_SESSION['item_product1_indicecommerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product1_indicecommerciaux_p2']))		{ $_SESSION['item_product1_indicecommerciaux_p2']	= $_POST['item_product1_indicecommerciaux_p2']; }		else {    $_SESSION['item_product1_indicecommerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product1_indicecommerciaux_p3']))		{ $_SESSION['item_product1_indicecommerciaux_p3']	= $_POST['item_product1_indicecommerciaux_p3']; }		else {    $_SESSION['item_product1_indicecommerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product1_indicecommerciaux_p4']))		{ $_SESSION['item_product1_indicecommerciaux_p4']	= $_POST['item_product1_indicecommerciaux_p4']; }		else {    $_SESSION['item_product1_indicecommerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product1_indicecommerciaux_p5']))		{ $_SESSION['item_product1_indicecommerciaux_p5']	= $_POST['item_product1_indicecommerciaux_p5']; }		else {    $_SESSION['item_product1_indicecommerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product1_indicecommerciaux_p6']))		{ $_SESSION['item_product1_indicecommerciaux_p6']	= $_POST['item_product1_indicecommerciaux_p6']; }		else {    $_SESSION['item_product1_indicecommerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product1_creditclient_p1']))		{ $_SESSION['item_product1_creditclient_p1']	= $_POST['item_product1_creditclient_p1']; }		else {    $_SESSION['item_product1_creditclient_p1'] = 'non' ; }
if (isset($_POST['item_product1_creditclient_p2']))		{ $_SESSION['item_product1_creditclient_p2']	= $_POST['item_product1_creditclient_p2']; }		else {    $_SESSION['item_product1_creditclient_p2'] = 'non' ; }
if (isset($_POST['item_product1_creditclient_p3']))		{ $_SESSION['item_product1_creditclient_p3']	= $_POST['item_product1_creditclient_p3']; }		else {    $_SESSION['item_product1_creditclient_p3'] = 'non' ; }
if (isset($_POST['item_product1_creditclient_p4']))		{ $_SESSION['item_product1_creditclient_p4']	= $_POST['item_product1_creditclient_p4']; }		else {    $_SESSION['item_product1_creditclient_p4'] = 'non' ; }
if (isset($_POST['item_product1_creditclient_p5']))		{ $_SESSION['item_product1_creditclient_p5']	= $_POST['item_product1_creditclient_p5']; }		else {    $_SESSION['item_product1_creditclient_p5'] = 'non' ; }
if (isset($_POST['item_product1_creditclient_p6']))		{ $_SESSION['item_product1_creditclient_p6']	= $_POST['item_product1_creditclient_p6']; }		else {    $_SESSION['item_product1_creditclient_p6'] = 'non' ; }
if (isset($_POST['item_product1_pdv_p1']))		{ $_SESSION['item_product1_pdv_p1']	= $_POST['item_product1_pdv_p1']; }		else {    $_SESSION['item_product1_pdv_p1'] = 'non' ; }
if (isset($_POST['item_product1_pdv_p2']))		{ $_SESSION['item_product1_pdv_p2']	= $_POST['item_product1_pdv_p2']; }		else {    $_SESSION['item_product1_pdv_p2'] = 'non' ; }
if (isset($_POST['item_product1_pdv_p3']))		{ $_SESSION['item_product1_pdv_p3']	= $_POST['item_product1_pdv_p3']; }		else {    $_SESSION['item_product1_pdv_p3'] = 'non' ; }
if (isset($_POST['item_product1_pdv_p4']))		{ $_SESSION['item_product1_pdv_p4']	= $_POST['item_product1_pdv_p4']; }		else {    $_SESSION['item_product1_pdv_p4'] = 'non' ; }
if (isset($_POST['item_product1_pdv_p5']))		{ $_SESSION['item_product1_pdv_p5']	= $_POST['item_product1_pdv_p5']; }		else {    $_SESSION['item_product1_pdv_p5'] = 'non' ; }
if (isset($_POST['item_product1_pdv_p6']))		{ $_SESSION['item_product1_pdv_p6']	= $_POST['item_product1_pdv_p6']; }		else {    $_SESSION['item_product1_pdv_p6'] = 'non' ; }


if (isset($_POST['item_product2_licence_p1']))		{ $_SESSION['item_product2_licence_p1']	= $_POST['item_product2_licence_p1']; }		else {    $_SESSION['item_product2_licence_p1'] = 'non' ; }
if (isset($_POST['item_product2_licence_p2']))		{ $_SESSION['item_product2_licence_p2']	= $_POST['item_product2_licence_p2']; }		else {    $_SESSION['item_product2_licence_p2'] = 'non' ; }
if (isset($_POST['item_product2_licence_p3']))		{ $_SESSION['item_product2_licence_p3']	= $_POST['item_product2_licence_p3']; }		else {    $_SESSION['item_product2_licence_p3'] = 'non' ; }
if (isset($_POST['item_product2_licence_p4']))		{ $_SESSION['item_product2_licence_p4']	= $_POST['item_product2_licence_p4']; }		else {    $_SESSION['item_product2_licence_p4'] = 'non' ; }
if (isset($_POST['item_product2_licence_p5']))		{ $_SESSION['item_product2_licence_p5']	= $_POST['item_product2_licence_p5']; }		else {    $_SESSION['item_product2_licence_p5'] = 'non' ; }
if (isset($_POST['item_product2_licence_p6']))		{ $_SESSION['item_product2_licence_p6']	= $_POST['item_product2_licence_p6']; }		else {    $_SESSION['item_product2_licence_p6'] = 'non' ; }
if (isset($_POST['item_product2_production_p1'])) { $_SESSION['item_product2_production_p1']	= $_POST['item_product2_production_p1']; } else { $_SESSION['item_product2_production_p1'] = 'non' ; }
if (isset($_POST['item_product2_production_p2'])) { $_SESSION['item_product2_production_p2']	= $_POST['item_product2_production_p2']; } else { $_SESSION['item_product2_production_p2'] = 'non' ; }
if (isset($_POST['item_product2_production_p3'])) { $_SESSION['item_product2_production_p3']	= $_POST['item_product2_production_p3']; } else { $_SESSION['item_product2_production_p3'] = 'non' ; }
if (isset($_POST['item_product2_production_p4'])) { $_SESSION['item_product2_production_p4']	= $_POST['item_product2_production_p4']; } else { $_SESSION['item_product2_production_p4'] = 'non' ; }
if (isset($_POST['item_product2_production_p5'])) { $_SESSION['item_product2_production_p5']	= $_POST['item_product2_production_p5']; } else { $_SESSION['item_product2_production_p5'] = 'non' ; }
if (isset($_POST['item_product2_production_p6'])) { $_SESSION['item_product2_production_p6']	= $_POST['item_product2_production_p6']; } else { $_SESSION['item_product2_production_p6'] = 'non' ; }
if (isset($_POST['item_product2_qualite_p1']))		{ $_SESSION['item_product2_qualite_p1']	= $_POST['item_product2_qualite_p1']; }		else {    $_SESSION['item_product2_qualite_p1'] = 'non' ; }
if (isset($_POST['item_product2_qualite_p2']))		{ $_SESSION['item_product2_qualite_p2']	= $_POST['item_product2_qualite_p2']; }		else {    $_SESSION['item_product2_qualite_p2'] = 'non' ; }
if (isset($_POST['item_product2_qualite_p3']))		{ $_SESSION['item_product2_qualite_p3']	= $_POST['item_product2_qualite_p3']; }		else {    $_SESSION['item_product2_qualite_p3'] = 'non' ; }
if (isset($_POST['item_product2_qualite_p4']))		{ $_SESSION['item_product2_qualite_p4']	= $_POST['item_product2_qualite_p4']; }		else {    $_SESSION['item_product2_qualite_p4'] = 'non' ; }
if (isset($_POST['item_product2_qualite_p5']))		{ $_SESSION['item_product2_qualite_p5']	= $_POST['item_product2_qualite_p5']; }		else {    $_SESSION['item_product2_qualite_p5'] = 'non' ; }
if (isset($_POST['item_product2_qualite_p6']))		{ $_SESSION['item_product2_qualite_p6']	= $_POST['item_product2_qualite_p6']; }		else {    $_SESSION['item_product2_qualite_p6'] = 'non' ; }
if (isset($_POST['item_product2_soustraitance_p1'])) { $_SESSION['item_product2_soustraitance_p1'] = $_POST['item_product2_soustraitance_p1']; } else { $_SESSION['item_product2_soustraitance_p1'] = 'non' ; }
if (isset($_POST['item_product2_soustraitance_p2'])) { $_SESSION['item_product2_soustraitance_p2'] = $_POST['item_product2_soustraitance_p2']; } else { $_SESSION['item_product2_soustraitance_p2'] = 'non' ; }
if (isset($_POST['item_product2_soustraitance_p3'])) { $_SESSION['item_product2_soustraitance_p3'] = $_POST['item_product2_soustraitance_p3']; } else { $_SESSION['item_product2_soustraitance_p3'] = 'non' ; }
if (isset($_POST['item_product2_soustraitance_p4'])) { $_SESSION['item_product2_soustraitance_p4'] = $_POST['item_product2_soustraitance_p4']; } else { $_SESSION['item_product2_soustraitance_p4'] = 'non' ; }
if (isset($_POST['item_product2_soustraitance_p5'])) { $_SESSION['item_product2_soustraitance_p5'] = $_POST['item_product2_soustraitance_p5']; } else { $_SESSION['item_product2_soustraitance_p5'] = 'non' ; }
if (isset($_POST['item_product2_soustraitance_p6'])) { $_SESSION['item_product2_soustraitance_p6'] = $_POST['item_product2_soustraitance_p6']; } else { $_SESSION['item_product2_soustraitance_p6'] = 'non' ; }
if (isset($_POST['item_product2_budgetcom_p1']))		{ $_SESSION['item_product2_budgetcom_p1']	= $_POST['item_product2_budgetcom_p1']; }		else {    $_SESSION['item_product2_budgetcom_p1'] = 'non' ; }
if (isset($_POST['item_product2_budgetcom_p2']))		{ $_SESSION['item_product2_budgetcom_p2']	= $_POST['item_product2_budgetcom_p2']; }		else {    $_SESSION['item_product2_budgetcom_p2'] = 'non' ; }
if (isset($_POST['item_product2_budgetcom_p3']))		{ $_SESSION['item_product2_budgetcom_p3']	= $_POST['item_product2_budgetcom_p3']; }		else {    $_SESSION['item_product2_budgetcom_p3'] = 'non' ; }
if (isset($_POST['item_product2_budgetcom_p4']))		{ $_SESSION['item_product2_budgetcom_p4']	= $_POST['item_product2_budgetcom_p4']; }		else {    $_SESSION['item_product2_budgetcom_p4'] = 'non' ; }
if (isset($_POST['item_product2_budgetcom_p5']))		{ $_SESSION['item_product2_budgetcom_p5']	= $_POST['item_product2_budgetcom_p5']; }		else {    $_SESSION['item_product2_budgetcom_p5'] = 'non' ; }
if (isset($_POST['item_product2_budgetcom_p6']))		{ $_SESSION['item_product2_budgetcom_p6']	= $_POST['item_product2_budgetcom_p6']; }		else {    $_SESSION['item_product2_budgetcom_p6'] = 'non' ; }
if (isset($_POST['item_product2_commerciaux_p1']))		{ $_SESSION['item_product2_commerciaux_p1']	= $_POST['item_product2_commerciaux_p1']; }		else {    $_SESSION['item_product2_commerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product2_commerciaux_p2']))		{ $_SESSION['item_product2_commerciaux_p2']	= $_POST['item_product2_commerciaux_p2']; }		else {    $_SESSION['item_product2_commerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product2_commerciaux_p3']))		{ $_SESSION['item_product2_commerciaux_p3']	= $_POST['item_product2_commerciaux_p3']; }		else {    $_SESSION['item_product2_commerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product2_commerciaux_p4']))		{ $_SESSION['item_product2_commerciaux_p4']	= $_POST['item_product2_commerciaux_p4']; }		else {    $_SESSION['item_product2_commerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product2_commerciaux_p5']))		{ $_SESSION['item_product2_commerciaux_p5']	= $_POST['item_product2_commerciaux_p5']; }		else {    $_SESSION['item_product2_commerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product2_commerciaux_p6']))		{ $_SESSION['item_product2_commerciaux_p6']	= $_POST['item_product2_commerciaux_p6']; }		else {    $_SESSION['item_product2_commerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product2_indicecommerciaux_p1']))		{ $_SESSION['item_product2_indicecommerciaux_p1']	= $_POST['item_product2_indicecommerciaux_p1']; }		else {    $_SESSION['item_product2_indicecommerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product2_indicecommerciaux_p2']))		{ $_SESSION['item_product2_indicecommerciaux_p2']	= $_POST['item_product2_indicecommerciaux_p2']; }		else {    $_SESSION['item_product2_indicecommerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product2_indicecommerciaux_p3']))		{ $_SESSION['item_product2_indicecommerciaux_p3']	= $_POST['item_product2_indicecommerciaux_p3']; }		else {    $_SESSION['item_product2_indicecommerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product2_indicecommerciaux_p4']))		{ $_SESSION['item_product2_indicecommerciaux_p4']	= $_POST['item_product2_indicecommerciaux_p4']; }		else {    $_SESSION['item_product2_indicecommerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product2_indicecommerciaux_p5']))		{ $_SESSION['item_product2_indicecommerciaux_p5']	= $_POST['item_product2_indicecommerciaux_p5']; }		else {    $_SESSION['item_product2_indicecommerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product2_indicecommerciaux_p6']))		{ $_SESSION['item_product2_indicecommerciaux_p6']	= $_POST['item_product2_indicecommerciaux_p6']; }		else {    $_SESSION['item_product2_indicecommerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product2_creditclient_p1']))		{ $_SESSION['item_product2_creditclient_p1']	= $_POST['item_product2_creditclient_p1']; }		else {    $_SESSION['item_product2_creditclient_p1'] = 'non' ; }
if (isset($_POST['item_product2_creditclient_p2']))		{ $_SESSION['item_product2_creditclient_p2']	= $_POST['item_product2_creditclient_p2']; }		else {    $_SESSION['item_product2_creditclient_p2'] = 'non' ; }
if (isset($_POST['item_product2_creditclient_p3']))		{ $_SESSION['item_product2_creditclient_p3']	= $_POST['item_product2_creditclient_p3']; }		else {    $_SESSION['item_product2_creditclient_p3'] = 'non' ; }
if (isset($_POST['item_product2_creditclient_p4']))		{ $_SESSION['item_product2_creditclient_p4']	= $_POST['item_product2_creditclient_p4']; }		else {    $_SESSION['item_product2_creditclient_p4'] = 'non' ; }
if (isset($_POST['item_product2_creditclient_p5']))		{ $_SESSION['item_product2_creditclient_p5']	= $_POST['item_product2_creditclient_p5']; }		else {    $_SESSION['item_product2_creditclient_p5'] = 'non' ; }
if (isset($_POST['item_product2_creditclient_p6']))		{ $_SESSION['item_product2_creditclient_p6']	= $_POST['item_product2_creditclient_p6']; }		else {    $_SESSION['item_product2_creditclient_p6'] = 'non' ; }
if (isset($_POST['item_product2_pdv_p1']))		{ $_SESSION['item_product2_pdv_p1']	= $_POST['item_product2_pdv_p1']; }		else {    $_SESSION['item_product2_pdv_p1'] = 'non' ; }
if (isset($_POST['item_product2_pdv_p2']))		{ $_SESSION['item_product2_pdv_p2']	= $_POST['item_product2_pdv_p2']; }		else {    $_SESSION['item_product2_pdv_p2'] = 'non' ; }
if (isset($_POST['item_product2_pdv_p3']))		{ $_SESSION['item_product2_pdv_p3']	= $_POST['item_product2_pdv_p3']; }		else {    $_SESSION['item_product2_pdv_p3'] = 'non' ; }
if (isset($_POST['item_product2_pdv_p4']))		{ $_SESSION['item_product2_pdv_p4']	= $_POST['item_product2_pdv_p4']; }		else {    $_SESSION['item_product2_pdv_p4'] = 'non' ; }
if (isset($_POST['item_product2_pdv_p5']))		{ $_SESSION['item_product2_pdv_p5']	= $_POST['item_product2_pdv_p5']; }		else {    $_SESSION['item_product2_pdv_p5'] = 'non' ; }
if (isset($_POST['item_product2_pdv_p6']))		{ $_SESSION['item_product2_pdv_p6']	= $_POST['item_product2_pdv_p6']; }		else {    $_SESSION['item_product2_pdv_p6'] = 'non' ; }





if (isset($_POST['item_product3_licence_p1']))		{ $_SESSION['item_product3_licence_p1']	= $_POST['item_product3_licence_p1']; }		else {    $_SESSION['item_product3_licence_p1'] = 'non' ; }
if (isset($_POST['item_product3_licence_p2']))		{ $_SESSION['item_product3_licence_p2']	= $_POST['item_product3_licence_p2']; }		else {    $_SESSION['item_product3_licence_p2'] = 'non' ; }
if (isset($_POST['item_product3_licence_p3']))		{ $_SESSION['item_product3_licence_p3']	= $_POST['item_product3_licence_p3']; }		else {    $_SESSION['item_product3_licence_p3'] = 'non' ; }
if (isset($_POST['item_product3_licence_p4']))		{ $_SESSION['item_product3_licence_p4']	= $_POST['item_product3_licence_p4']; }		else {    $_SESSION['item_product3_licence_p4'] = 'non' ; }
if (isset($_POST['item_product3_licence_p5']))		{ $_SESSION['item_product3_licence_p5']	= $_POST['item_product3_licence_p5']; }		else {    $_SESSION['item_product3_licence_p5'] = 'non' ; }
if (isset($_POST['item_product3_licence_p6']))		{ $_SESSION['item_product3_licence_p6']	= $_POST['item_product3_licence_p6']; }		else {    $_SESSION['item_product3_licence_p6'] = 'non' ; }
if (isset($_POST['item_product3_production_p1'])) { $_SESSION['item_product3_production_p1']	= $_POST['item_product3_production_p1']; } else { $_SESSION['item_product3_production_p1'] = 'non' ; }
if (isset($_POST['item_product3_production_p2'])) { $_SESSION['item_product3_production_p2']	= $_POST['item_product3_production_p2']; } else { $_SESSION['item_product3_production_p2'] = 'non' ; }
if (isset($_POST['item_product3_production_p3'])) { $_SESSION['item_product3_production_p3']	= $_POST['item_product3_production_p3']; } else { $_SESSION['item_product3_production_p3'] = 'non' ; }
if (isset($_POST['item_product3_production_p4'])) { $_SESSION['item_product3_production_p4']	= $_POST['item_product3_production_p4']; } else { $_SESSION['item_product3_production_p4'] = 'non' ; }
if (isset($_POST['item_product3_production_p5'])) { $_SESSION['item_product3_production_p5']	= $_POST['item_product3_production_p5']; } else { $_SESSION['item_product3_production_p5'] = 'non' ; }
if (isset($_POST['item_product3_production_p6'])) { $_SESSION['item_product3_production_p6']	= $_POST['item_product3_production_p6']; } else { $_SESSION['item_product3_production_p6'] = 'non' ; }
if (isset($_POST['item_product3_qualite_p1']))		{ $_SESSION['item_product3_qualite_p1']	= $_POST['item_product3_qualite_p1']; }		else {    $_SESSION['item_product3_qualite_p1'] = 'non' ; }
if (isset($_POST['item_product3_qualite_p2']))		{ $_SESSION['item_product3_qualite_p2']	= $_POST['item_product3_qualite_p2']; }		else {    $_SESSION['item_product3_qualite_p2'] = 'non' ; }
if (isset($_POST['item_product3_qualite_p3']))		{ $_SESSION['item_product3_qualite_p3']	= $_POST['item_product3_qualite_p3']; }		else {    $_SESSION['item_product3_qualite_p3'] = 'non' ; }
if (isset($_POST['item_product3_qualite_p4']))		{ $_SESSION['item_product3_qualite_p4']	= $_POST['item_product3_qualite_p4']; }		else {    $_SESSION['item_product3_qualite_p4'] = 'non' ; }
if (isset($_POST['item_product3_qualite_p5']))		{ $_SESSION['item_product3_qualite_p5']	= $_POST['item_product3_qualite_p5']; }		else {    $_SESSION['item_product3_qualite_p5'] = 'non' ; }
if (isset($_POST['item_product3_qualite_p6']))		{ $_SESSION['item_product3_qualite_p6']	= $_POST['item_product3_qualite_p6']; }		else {    $_SESSION['item_product3_qualite_p6'] = 'non' ; }
if (isset($_POST['item_product3_soustraitance_p1'])) { $_SESSION['item_product3_soustraitance_p1'] = $_POST['item_product3_soustraitance_p1']; } else { $_SESSION['item_product3_soustraitance_p1'] = 'non' ; }
if (isset($_POST['item_product3_soustraitance_p2'])) { $_SESSION['item_product3_soustraitance_p2'] = $_POST['item_product3_soustraitance_p2']; } else { $_SESSION['item_product3_soustraitance_p2'] = 'non' ; }
if (isset($_POST['item_product3_soustraitance_p3'])) { $_SESSION['item_product3_soustraitance_p3'] = $_POST['item_product3_soustraitance_p3']; } else { $_SESSION['item_product3_soustraitance_p3'] = 'non' ; }
if (isset($_POST['item_product3_soustraitance_p4'])) { $_SESSION['item_product3_soustraitance_p4'] = $_POST['item_product3_soustraitance_p4']; } else { $_SESSION['item_product3_soustraitance_p4'] = 'non' ; }
if (isset($_POST['item_product3_soustraitance_p5'])) { $_SESSION['item_product3_soustraitance_p5'] = $_POST['item_product3_soustraitance_p5']; } else { $_SESSION['item_product3_soustraitance_p5'] = 'non' ; }
if (isset($_POST['item_product3_soustraitance_p6'])) { $_SESSION['item_product3_soustraitance_p6'] = $_POST['item_product3_soustraitance_p6']; } else { $_SESSION['item_product3_soustraitance_p6'] = 'non' ; }
if (isset($_POST['item_product3_budgetcom_p1']))		{ $_SESSION['item_product3_budgetcom_p1']	= $_POST['item_product3_budgetcom_p1']; }		else {    $_SESSION['item_product3_budgetcom_p1'] = 'non' ; }
if (isset($_POST['item_product3_budgetcom_p2']))		{ $_SESSION['item_product3_budgetcom_p2']	= $_POST['item_product3_budgetcom_p2']; }		else {    $_SESSION['item_product3_budgetcom_p2'] = 'non' ; }
if (isset($_POST['item_product3_budgetcom_p3']))		{ $_SESSION['item_product3_budgetcom_p3']	= $_POST['item_product3_budgetcom_p3']; }		else {    $_SESSION['item_product3_budgetcom_p3'] = 'non' ; }
if (isset($_POST['item_product3_budgetcom_p4']))		{ $_SESSION['item_product3_budgetcom_p4']	= $_POST['item_product3_budgetcom_p4']; }		else {    $_SESSION['item_product3_budgetcom_p4'] = 'non' ; }
if (isset($_POST['item_product3_budgetcom_p5']))		{ $_SESSION['item_product3_budgetcom_p5']	= $_POST['item_product3_budgetcom_p5']; }		else {    $_SESSION['item_product3_budgetcom_p5'] = 'non' ; }
if (isset($_POST['item_product3_budgetcom_p6']))		{ $_SESSION['item_product3_budgetcom_p6']	= $_POST['item_product3_budgetcom_p6']; }		else {    $_SESSION['item_product3_budgetcom_p6'] = 'non' ; }
if (isset($_POST['item_product3_commerciaux_p1']))		{ $_SESSION['item_product3_commerciaux_p1']	= $_POST['item_product3_commerciaux_p1']; }		else {    $_SESSION['item_product3_commerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product3_commerciaux_p2']))		{ $_SESSION['item_product3_commerciaux_p2']	= $_POST['item_product3_commerciaux_p2']; }		else {    $_SESSION['item_product3_commerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product3_commerciaux_p3']))		{ $_SESSION['item_product3_commerciaux_p3']	= $_POST['item_product3_commerciaux_p3']; }		else {    $_SESSION['item_product3_commerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product3_commerciaux_p4']))		{ $_SESSION['item_product3_commerciaux_p4']	= $_POST['item_product3_commerciaux_p4']; }		else {    $_SESSION['item_product3_commerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product3_commerciaux_p5']))		{ $_SESSION['item_product3_commerciaux_p5']	= $_POST['item_product3_commerciaux_p5']; }		else {    $_SESSION['item_product3_commerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product3_commerciaux_p6']))		{ $_SESSION['item_product3_commerciaux_p6']	= $_POST['item_product3_commerciaux_p6']; }		else {    $_SESSION['item_product3_commerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product3_indicecommerciaux_p1']))		{ $_SESSION['item_product3_indicecommerciaux_p1']	= $_POST['item_product3_indicecommerciaux_p1']; }		else {    $_SESSION['item_product3_indicecommerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product3_indicecommerciaux_p2']))		{ $_SESSION['item_product3_indicecommerciaux_p2']	= $_POST['item_product3_indicecommerciaux_p2']; }		else {    $_SESSION['item_product3_indicecommerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product3_indicecommerciaux_p3']))		{ $_SESSION['item_product3_indicecommerciaux_p3']	= $_POST['item_product3_indicecommerciaux_p3']; }		else {    $_SESSION['item_product3_indicecommerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product3_indicecommerciaux_p4']))		{ $_SESSION['item_product3_indicecommerciaux_p4']	= $_POST['item_product3_indicecommerciaux_p4']; }		else {    $_SESSION['item_product3_indicecommerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product3_indicecommerciaux_p5']))		{ $_SESSION['item_product3_indicecommerciaux_p5']	= $_POST['item_product3_indicecommerciaux_p5']; }		else {    $_SESSION['item_product3_indicecommerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product3_indicecommerciaux_p6']))		{ $_SESSION['item_product3_indicecommerciaux_p6']	= $_POST['item_product3_indicecommerciaux_p6']; }		else {    $_SESSION['item_product3_indicecommerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product3_creditclient_p1']))		{ $_SESSION['item_product3_creditclient_p1']	= $_POST['item_product3_creditclient_p1']; }		else {    $_SESSION['item_product3_creditclient_p1'] = 'non' ; }
if (isset($_POST['item_product3_creditclient_p2']))		{ $_SESSION['item_product3_creditclient_p2']	= $_POST['item_product3_creditclient_p2']; }		else {    $_SESSION['item_product3_creditclient_p2'] = 'non' ; }
if (isset($_POST['item_product3_creditclient_p3']))		{ $_SESSION['item_product3_creditclient_p3']	= $_POST['item_product3_creditclient_p3']; }		else {    $_SESSION['item_product3_creditclient_p3'] = 'non' ; }
if (isset($_POST['item_product3_creditclient_p4']))		{ $_SESSION['item_product3_creditclient_p4']	= $_POST['item_product3_creditclient_p4']; }		else {    $_SESSION['item_product3_creditclient_p4'] = 'non' ; }
if (isset($_POST['item_product3_creditclient_p5']))		{ $_SESSION['item_product3_creditclient_p5']	= $_POST['item_product3_creditclient_p5']; }		else {    $_SESSION['item_product3_creditclient_p5'] = 'non' ; }
if (isset($_POST['item_product3_creditclient_p6']))		{ $_SESSION['item_product3_creditclient_p6']	= $_POST['item_product3_creditclient_p6']; }		else {    $_SESSION['item_product3_creditclient_p6'] = 'non' ; }
if (isset($_POST['item_product3_pdv_p1']))		{ $_SESSION['item_product3_pdv_p1']	= $_POST['item_product3_pdv_p1']; }		else {    $_SESSION['item_product3_pdv_p1'] = 'non' ; }
if (isset($_POST['item_product3_pdv_p2']))		{ $_SESSION['item_product3_pdv_p2']	= $_POST['item_product3_pdv_p2']; }		else {    $_SESSION['item_product3_pdv_p2'] = 'non' ; }
if (isset($_POST['item_product3_pdv_p3']))		{ $_SESSION['item_product3_pdv_p3']	= $_POST['item_product3_pdv_p3']; }		else {    $_SESSION['item_product3_pdv_p3'] = 'non' ; }
if (isset($_POST['item_product3_pdv_p4']))		{ $_SESSION['item_product3_pdv_p4']	= $_POST['item_product3_pdv_p4']; }		else {    $_SESSION['item_product3_pdv_p4'] = 'non' ; }
if (isset($_POST['item_product3_pdv_p5']))		{ $_SESSION['item_product3_pdv_p5']	= $_POST['item_product3_pdv_p5']; }		else {    $_SESSION['item_product3_pdv_p5'] = 'non' ; }
if (isset($_POST['item_product3_pdv_p6']))		{ $_SESSION['item_product3_pdv_p6']	= $_POST['item_product3_pdv_p6']; }		else {    $_SESSION['item_product3_pdv_p6'] = 'non' ; }


if (isset($_POST['item_product4_licence_p1']))		{ $_SESSION['item_product4_licence_p1']	= $_POST['item_product4_licence_p1']; }		else {    $_SESSION['item_product4_licence_p1'] = 'non' ; }
if (isset($_POST['item_product4_licence_p2']))		{ $_SESSION['item_product4_licence_p2']	= $_POST['item_product4_licence_p2']; }		else {    $_SESSION['item_product4_licence_p2'] = 'non' ; }
if (isset($_POST['item_product4_licence_p3']))		{ $_SESSION['item_product4_licence_p3']	= $_POST['item_product4_licence_p3']; }		else {    $_SESSION['item_product4_licence_p3'] = 'non' ; }
if (isset($_POST['item_product4_licence_p4']))		{ $_SESSION['item_product4_licence_p4']	= $_POST['item_product4_licence_p4']; }		else {    $_SESSION['item_product4_licence_p4'] = 'non' ; }
if (isset($_POST['item_product4_licence_p5']))		{ $_SESSION['item_product4_licence_p5']	= $_POST['item_product4_licence_p5']; }		else {    $_SESSION['item_product4_licence_p5'] = 'non' ; }
if (isset($_POST['item_product4_licence_p6']))		{ $_SESSION['item_product4_licence_p6']	= $_POST['item_product4_licence_p6']; }		else {    $_SESSION['item_product4_licence_p6'] = 'non' ; }
if (isset($_POST['item_product4_production_p1'])) { $_SESSION['item_product4_production_p1']	= $_POST['item_product4_production_p1']; } else { $_SESSION['item_product4_production_p1'] = 'non' ; }
if (isset($_POST['item_product4_production_p2'])) { $_SESSION['item_product4_production_p2']	= $_POST['item_product4_production_p2']; } else { $_SESSION['item_product4_production_p2'] = 'non' ; }
if (isset($_POST['item_product4_production_p3'])) { $_SESSION['item_product4_production_p3']	= $_POST['item_product4_production_p3']; } else { $_SESSION['item_product4_production_p3'] = 'non' ; }
if (isset($_POST['item_product4_production_p4'])) { $_SESSION['item_product4_production_p4']	= $_POST['item_product4_production_p4']; } else { $_SESSION['item_product4_production_p4'] = 'non' ; }
if (isset($_POST['item_product4_production_p5'])) { $_SESSION['item_product4_production_p5']	= $_POST['item_product4_production_p5']; } else { $_SESSION['item_product4_production_p5'] = 'non' ; }
if (isset($_POST['item_product4_production_p6'])) { $_SESSION['item_product4_production_p6']	= $_POST['item_product4_production_p6']; } else { $_SESSION['item_product4_production_p6'] = 'non' ; }
if (isset($_POST['item_product4_qualite_p1']))		{ $_SESSION['item_product4_qualite_p1']	= $_POST['item_product4_qualite_p1']; }		else {    $_SESSION['item_product4_qualite_p1'] = 'non' ; }
if (isset($_POST['item_product4_qualite_p2']))		{ $_SESSION['item_product4_qualite_p2']	= $_POST['item_product4_qualite_p2']; }		else {    $_SESSION['item_product4_qualite_p2'] = 'non' ; }
if (isset($_POST['item_product4_qualite_p3']))		{ $_SESSION['item_product4_qualite_p3']	= $_POST['item_product4_qualite_p3']; }		else {    $_SESSION['item_product4_qualite_p3'] = 'non' ; }
if (isset($_POST['item_product4_qualite_p4']))		{ $_SESSION['item_product4_qualite_p4']	= $_POST['item_product4_qualite_p4']; }		else {    $_SESSION['item_product4_qualite_p4'] = 'non' ; }
if (isset($_POST['item_product4_qualite_p5']))		{ $_SESSION['item_product4_qualite_p5']	= $_POST['item_product4_qualite_p5']; }		else {    $_SESSION['item_product4_qualite_p5'] = 'non' ; }
if (isset($_POST['item_product4_qualite_p6']))		{ $_SESSION['item_product4_qualite_p6']	= $_POST['item_product4_qualite_p6']; }		else {    $_SESSION['item_product4_qualite_p6'] = 'non' ; }
if (isset($_POST['item_product4_soustraitance_p1'])) { $_SESSION['item_product4_soustraitance_p1'] = $_POST['item_product4_soustraitance_p1']; } else { $_SESSION['item_product4_soustraitance_p1'] = 'non' ; }
if (isset($_POST['item_product4_soustraitance_p2'])) { $_SESSION['item_product4_soustraitance_p2'] = $_POST['item_product4_soustraitance_p2']; } else { $_SESSION['item_product4_soustraitance_p2'] = 'non' ; }
if (isset($_POST['item_product4_soustraitance_p3'])) { $_SESSION['item_product4_soustraitance_p3'] = $_POST['item_product4_soustraitance_p3']; } else { $_SESSION['item_product4_soustraitance_p3'] = 'non' ; }
if (isset($_POST['item_product4_soustraitance_p4'])) { $_SESSION['item_product4_soustraitance_p4'] = $_POST['item_product4_soustraitance_p4']; } else { $_SESSION['item_product4_soustraitance_p4'] = 'non' ; }
if (isset($_POST['item_product4_soustraitance_p5'])) { $_SESSION['item_product4_soustraitance_p5'] = $_POST['item_product4_soustraitance_p5']; } else { $_SESSION['item_product4_soustraitance_p5'] = 'non' ; }
if (isset($_POST['item_product4_soustraitance_p6'])) { $_SESSION['item_product4_soustraitance_p6'] = $_POST['item_product4_soustraitance_p6']; } else { $_SESSION['item_product4_soustraitance_p6'] = 'non' ; }
if (isset($_POST['item_product4_budgetcom_p1']))		{ $_SESSION['item_product4_budgetcom_p1']	= $_POST['item_product4_budgetcom_p1']; }		else {    $_SESSION['item_product4_budgetcom_p1'] = 'non' ; }
if (isset($_POST['item_product4_budgetcom_p2']))		{ $_SESSION['item_product4_budgetcom_p2']	= $_POST['item_product4_budgetcom_p2']; }		else {    $_SESSION['item_product4_budgetcom_p2'] = 'non' ; }
if (isset($_POST['item_product4_budgetcom_p3']))		{ $_SESSION['item_product4_budgetcom_p3']	= $_POST['item_product4_budgetcom_p3']; }		else {    $_SESSION['item_product4_budgetcom_p3'] = 'non' ; }
if (isset($_POST['item_product4_budgetcom_p4']))		{ $_SESSION['item_product4_budgetcom_p4']	= $_POST['item_product4_budgetcom_p4']; }		else {    $_SESSION['item_product4_budgetcom_p4'] = 'non' ; }
if (isset($_POST['item_product4_budgetcom_p5']))		{ $_SESSION['item_product4_budgetcom_p5']	= $_POST['item_product4_budgetcom_p5']; }		else {    $_SESSION['item_product4_budgetcom_p5'] = 'non' ; }
if (isset($_POST['item_product4_budgetcom_p6']))		{ $_SESSION['item_product4_budgetcom_p6']	= $_POST['item_product4_budgetcom_p6']; }		else {    $_SESSION['item_product4_budgetcom_p6'] = 'non' ; }
if (isset($_POST['item_product4_commerciaux_p1']))		{ $_SESSION['item_product4_commerciaux_p1']	= $_POST['item_product4_commerciaux_p1']; }		else {    $_SESSION['item_product4_commerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product4_commerciaux_p2']))		{ $_SESSION['item_product4_commerciaux_p2']	= $_POST['item_product4_commerciaux_p2']; }		else {    $_SESSION['item_product4_commerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product4_commerciaux_p3']))		{ $_SESSION['item_product4_commerciaux_p3']	= $_POST['item_product4_commerciaux_p3']; }		else {    $_SESSION['item_product4_commerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product4_commerciaux_p4']))		{ $_SESSION['item_product4_commerciaux_p4']	= $_POST['item_product4_commerciaux_p4']; }		else {    $_SESSION['item_product4_commerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product4_commerciaux_p5']))		{ $_SESSION['item_product4_commerciaux_p5']	= $_POST['item_product4_commerciaux_p5']; }		else {    $_SESSION['item_product4_commerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product4_commerciaux_p6']))		{ $_SESSION['item_product4_commerciaux_p6']	= $_POST['item_product4_commerciaux_p6']; }		else {    $_SESSION['item_product4_commerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product4_indicecommerciaux_p1']))		{ $_SESSION['item_product4_indicecommerciaux_p1']	= $_POST['item_product4_indicecommerciaux_p1']; }		else {    $_SESSION['item_product4_indicecommerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product4_indicecommerciaux_p2']))		{ $_SESSION['item_product4_indicecommerciaux_p2']	= $_POST['item_product4_indicecommerciaux_p2']; }		else {    $_SESSION['item_product4_indicecommerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product4_indicecommerciaux_p3']))		{ $_SESSION['item_product4_indicecommerciaux_p3']	= $_POST['item_product4_indicecommerciaux_p3']; }		else {    $_SESSION['item_product4_indicecommerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product4_indicecommerciaux_p4']))		{ $_SESSION['item_product4_indicecommerciaux_p4']	= $_POST['item_product4_indicecommerciaux_p4']; }		else {    $_SESSION['item_product4_indicecommerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product4_indicecommerciaux_p5']))		{ $_SESSION['item_product4_indicecommerciaux_p5']	= $_POST['item_product4_indicecommerciaux_p5']; }		else {    $_SESSION['item_product4_indicecommerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product4_indicecommerciaux_p6']))		{ $_SESSION['item_product4_indicecommerciaux_p6']	= $_POST['item_product4_indicecommerciaux_p6']; }		else {    $_SESSION['item_product4_indicecommerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product4_creditclient_p1']))		{ $_SESSION['item_product4_creditclient_p1']	= $_POST['item_product4_creditclient_p1']; }		else {    $_SESSION['item_product4_creditclient_p1'] = 'non' ; }
if (isset($_POST['item_product4_creditclient_p2']))		{ $_SESSION['item_product4_creditclient_p2']	= $_POST['item_product4_creditclient_p2']; }		else {    $_SESSION['item_product4_creditclient_p2'] = 'non' ; }
if (isset($_POST['item_product4_creditclient_p3']))		{ $_SESSION['item_product4_creditclient_p3']	= $_POST['item_product4_creditclient_p3']; }		else {    $_SESSION['item_product4_creditclient_p3'] = 'non' ; }
if (isset($_POST['item_product4_creditclient_p4']))		{ $_SESSION['item_product4_creditclient_p4']	= $_POST['item_product4_creditclient_p4']; }		else {    $_SESSION['item_product4_creditclient_p4'] = 'non' ; }
if (isset($_POST['item_product4_creditclient_p5']))		{ $_SESSION['item_product4_creditclient_p5']	= $_POST['item_product4_creditclient_p5']; }		else {    $_SESSION['item_product4_creditclient_p5'] = 'non' ; }
if (isset($_POST['item_product4_creditclient_p6']))		{ $_SESSION['item_product4_creditclient_p6']	= $_POST['item_product4_creditclient_p6']; }		else {    $_SESSION['item_product4_creditclient_p6'] = 'non' ; }
if (isset($_POST['item_product4_pdv_p1']))		{ $_SESSION['item_product4_pdv_p1']	= $_POST['item_product4_pdv_p1']; }		else {    $_SESSION['item_product4_pdv_p1'] = 'non' ; }
if (isset($_POST['item_product4_pdv_p2']))		{ $_SESSION['item_product4_pdv_p2']	= $_POST['item_product4_pdv_p2']; }		else {    $_SESSION['item_product4_pdv_p2'] = 'non' ; }
if (isset($_POST['item_product4_pdv_p3']))		{ $_SESSION['item_product4_pdv_p3']	= $_POST['item_product4_pdv_p3']; }		else {    $_SESSION['item_product4_pdv_p3'] = 'non' ; }
if (isset($_POST['item_product4_pdv_p4']))		{ $_SESSION['item_product4_pdv_p4']	= $_POST['item_product4_pdv_p4']; }		else {    $_SESSION['item_product4_pdv_p4'] = 'non' ; }
if (isset($_POST['item_product4_pdv_p5']))		{ $_SESSION['item_product4_pdv_p5']	= $_POST['item_product4_pdv_p5']; }		else {    $_SESSION['item_product4_pdv_p5'] = 'non' ; }
if (isset($_POST['item_product4_pdv_p6']))		{ $_SESSION['item_product4_pdv_p6']	= $_POST['item_product4_pdv_p6']; }		else {    $_SESSION['item_product4_pdv_p6'] = 'non' ; }



if (isset($_POST['item_product5_licence_p1']))		{ $_SESSION['item_product5_licence_p1']	= $_POST['item_product5_licence_p1']; }		else {    $_SESSION['item_product5_licence_p1'] = 'non' ; }
if (isset($_POST['item_product5_licence_p2']))		{ $_SESSION['item_product5_licence_p2']	= $_POST['item_product5_licence_p2']; }		else {    $_SESSION['item_product5_licence_p2'] = 'non' ; }
if (isset($_POST['item_product5_licence_p3']))		{ $_SESSION['item_product5_licence_p3']	= $_POST['item_product5_licence_p3']; }		else {    $_SESSION['item_product5_licence_p3'] = 'non' ; }
if (isset($_POST['item_product5_licence_p4']))		{ $_SESSION['item_product5_licence_p4']	= $_POST['item_product5_licence_p4']; }		else {    $_SESSION['item_product5_licence_p4'] = 'non' ; }
if (isset($_POST['item_product5_licence_p5']))		{ $_SESSION['item_product5_licence_p5']	= $_POST['item_product5_licence_p5']; }		else {    $_SESSION['item_product5_licence_p5'] = 'non' ; }
if (isset($_POST['item_product5_licence_p6']))		{ $_SESSION['item_product5_licence_p6']	= $_POST['item_product5_licence_p6']; }		else {    $_SESSION['item_product5_licence_p6'] = 'non' ; }
if (isset($_POST['item_product5_production_p1'])) { $_SESSION['item_product5_production_p1']	= $_POST['item_product5_production_p1']; } else { $_SESSION['item_product5_production_p1'] = 'non' ; }
if (isset($_POST['item_product5_production_p2'])) { $_SESSION['item_product5_production_p2']	= $_POST['item_product5_production_p2']; } else { $_SESSION['item_product5_production_p2'] = 'non' ; }
if (isset($_POST['item_product5_production_p3'])) { $_SESSION['item_product5_production_p3']	= $_POST['item_product5_production_p3']; } else { $_SESSION['item_product5_production_p3'] = 'non' ; }
if (isset($_POST['item_product5_production_p4'])) { $_SESSION['item_product5_production_p4']	= $_POST['item_product5_production_p4']; } else { $_SESSION['item_product5_production_p4'] = 'non' ; }
if (isset($_POST['item_product5_production_p5'])) { $_SESSION['item_product5_production_p5']	= $_POST['item_product5_production_p5']; } else { $_SESSION['item_product5_production_p5'] = 'non' ; }
if (isset($_POST['item_product5_production_p6'])) { $_SESSION['item_product5_production_p6']	= $_POST['item_product5_production_p6']; } else { $_SESSION['item_product5_production_p6'] = 'non' ; }
if (isset($_POST['item_product5_qualite_p1']))		{ $_SESSION['item_product5_qualite_p1']	= $_POST['item_product5_qualite_p1']; }		else {    $_SESSION['item_product5_qualite_p1'] = 'non' ; }
if (isset($_POST['item_product5_qualite_p2']))		{ $_SESSION['item_product5_qualite_p2']	= $_POST['item_product5_qualite_p2']; }		else {    $_SESSION['item_product5_qualite_p2'] = 'non' ; }
if (isset($_POST['item_product5_qualite_p3']))		{ $_SESSION['item_product5_qualite_p3']	= $_POST['item_product5_qualite_p3']; }		else {    $_SESSION['item_product5_qualite_p3'] = 'non' ; }
if (isset($_POST['item_product5_qualite_p4']))		{ $_SESSION['item_product5_qualite_p4']	= $_POST['item_product5_qualite_p4']; }		else {    $_SESSION['item_product5_qualite_p4'] = 'non' ; }
if (isset($_POST['item_product5_qualite_p5']))		{ $_SESSION['item_product5_qualite_p5']	= $_POST['item_product5_qualite_p5']; }		else {    $_SESSION['item_product5_qualite_p5'] = 'non' ; }
if (isset($_POST['item_product5_qualite_p6']))		{ $_SESSION['item_product5_qualite_p6']	= $_POST['item_product5_qualite_p6']; }		else {    $_SESSION['item_product5_qualite_p6'] = 'non' ; }
if (isset($_POST['item_product5_soustraitance_p1'])) { $_SESSION['item_product5_soustraitance_p1'] = $_POST['item_product5_soustraitance_p1']; } else { $_SESSION['item_product5_soustraitance_p1'] = 'non' ; }
if (isset($_POST['item_product5_soustraitance_p2'])) { $_SESSION['item_product5_soustraitance_p2'] = $_POST['item_product5_soustraitance_p2']; } else { $_SESSION['item_product5_soustraitance_p2'] = 'non' ; }
if (isset($_POST['item_product5_soustraitance_p3'])) { $_SESSION['item_product5_soustraitance_p3'] = $_POST['item_product5_soustraitance_p3']; } else { $_SESSION['item_product5_soustraitance_p3'] = 'non' ; }
if (isset($_POST['item_product5_soustraitance_p4'])) { $_SESSION['item_product5_soustraitance_p4'] = $_POST['item_product5_soustraitance_p4']; } else { $_SESSION['item_product5_soustraitance_p4'] = 'non' ; }
if (isset($_POST['item_product5_soustraitance_p5'])) { $_SESSION['item_product5_soustraitance_p5'] = $_POST['item_product5_soustraitance_p5']; } else { $_SESSION['item_product5_soustraitance_p5'] = 'non' ; }
if (isset($_POST['item_product5_soustraitance_p6'])) { $_SESSION['item_product5_soustraitance_p6'] = $_POST['item_product5_soustraitance_p6']; } else { $_SESSION['item_product5_soustraitance_p6'] = 'non' ; }
if (isset($_POST['item_product5_budgetcom_p1']))		{ $_SESSION['item_product5_budgetcom_p1']	= $_POST['item_product5_budgetcom_p1']; }		else {    $_SESSION['item_product5_budgetcom_p1'] = 'non' ; }
if (isset($_POST['item_product5_budgetcom_p2']))		{ $_SESSION['item_product5_budgetcom_p2']	= $_POST['item_product5_budgetcom_p2']; }		else {    $_SESSION['item_product5_budgetcom_p2'] = 'non' ; }
if (isset($_POST['item_product5_budgetcom_p3']))		{ $_SESSION['item_product5_budgetcom_p3']	= $_POST['item_product5_budgetcom_p3']; }		else {    $_SESSION['item_product5_budgetcom_p3'] = 'non' ; }
if (isset($_POST['item_product5_budgetcom_p4']))		{ $_SESSION['item_product5_budgetcom_p4']	= $_POST['item_product5_budgetcom_p4']; }		else {    $_SESSION['item_product5_budgetcom_p4'] = 'non' ; }
if (isset($_POST['item_product5_budgetcom_p5']))		{ $_SESSION['item_product5_budgetcom_p5']	= $_POST['item_product5_budgetcom_p5']; }		else {    $_SESSION['item_product5_budgetcom_p5'] = 'non' ; }
if (isset($_POST['item_product5_budgetcom_p6']))		{ $_SESSION['item_product5_budgetcom_p6']	= $_POST['item_product5_budgetcom_p6']; }		else {    $_SESSION['item_product5_budgetcom_p6'] = 'non' ; }
if (isset($_POST['item_product5_commerciaux_p1']))		{ $_SESSION['item_product5_commerciaux_p1']	= $_POST['item_product5_commerciaux_p1']; }		else {    $_SESSION['item_product5_commerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product5_commerciaux_p2']))		{ $_SESSION['item_product5_commerciaux_p2']	= $_POST['item_product5_commerciaux_p2']; }		else {    $_SESSION['item_product5_commerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product5_commerciaux_p3']))		{ $_SESSION['item_product5_commerciaux_p3']	= $_POST['item_product5_commerciaux_p3']; }		else {    $_SESSION['item_product5_commerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product5_commerciaux_p4']))		{ $_SESSION['item_product5_commerciaux_p4']	= $_POST['item_product5_commerciaux_p4']; }		else {    $_SESSION['item_product5_commerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product5_commerciaux_p5']))		{ $_SESSION['item_product5_commerciaux_p5']	= $_POST['item_product5_commerciaux_p5']; }		else {    $_SESSION['item_product5_commerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product5_commerciaux_p6']))		{ $_SESSION['item_product5_commerciaux_p6']	= $_POST['item_product5_commerciaux_p6']; }		else {    $_SESSION['item_product5_commerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product5_indicecommerciaux_p1']))		{ $_SESSION['item_product5_indicecommerciaux_p1']	= $_POST['item_product5_indicecommerciaux_p1']; }		else {    $_SESSION['item_product5_indicecommerciaux_p1'] = 'non' ; }
if (isset($_POST['item_product5_indicecommerciaux_p2']))		{ $_SESSION['item_product5_indicecommerciaux_p2']	= $_POST['item_product5_indicecommerciaux_p2']; }		else {    $_SESSION['item_product5_indicecommerciaux_p2'] = 'non' ; }
if (isset($_POST['item_product5_indicecommerciaux_p3']))		{ $_SESSION['item_product5_indicecommerciaux_p3']	= $_POST['item_product5_indicecommerciaux_p3']; }		else {    $_SESSION['item_product5_indicecommerciaux_p3'] = 'non' ; }
if (isset($_POST['item_product5_indicecommerciaux_p4']))		{ $_SESSION['item_product5_indicecommerciaux_p4']	= $_POST['item_product5_indicecommerciaux_p4']; }		else {    $_SESSION['item_product5_indicecommerciaux_p4'] = 'non' ; }
if (isset($_POST['item_product5_indicecommerciaux_p5']))		{ $_SESSION['item_product5_indicecommerciaux_p5']	= $_POST['item_product5_indicecommerciaux_p5']; }		else {    $_SESSION['item_product5_indicecommerciaux_p5'] = 'non' ; }
if (isset($_POST['item_product5_indicecommerciaux_p6']))		{ $_SESSION['item_product5_indicecommerciaux_p6']	= $_POST['item_product5_indicecommerciaux_p6']; }		else {    $_SESSION['item_product5_indicecommerciaux_p6'] = 'non' ; }
if (isset($_POST['item_product5_creditclient_p1']))		{ $_SESSION['item_product5_creditclient_p1']	= $_POST['item_product5_creditclient_p1']; }		else {    $_SESSION['item_product5_creditclient_p1'] = 'non' ; }
if (isset($_POST['item_product5_creditclient_p2']))		{ $_SESSION['item_product5_creditclient_p2']	= $_POST['item_product5_creditclient_p2']; }		else {    $_SESSION['item_product5_creditclient_p2'] = 'non' ; }
if (isset($_POST['item_product5_creditclient_p3']))		{ $_SESSION['item_product5_creditclient_p3']	= $_POST['item_product5_creditclient_p3']; }		else {    $_SESSION['item_product5_creditclient_p3'] = 'non' ; }
if (isset($_POST['item_product5_creditclient_p4']))		{ $_SESSION['item_product5_creditclient_p4']	= $_POST['item_product5_creditclient_p4']; }		else {    $_SESSION['item_product5_creditclient_p4'] = 'non' ; }
if (isset($_POST['item_product5_creditclient_p5']))		{ $_SESSION['item_product5_creditclient_p5']	= $_POST['item_product5_creditclient_p5']; }		else {    $_SESSION['item_product5_creditclient_p5'] = 'non' ; }
if (isset($_POST['item_product5_creditclient_p6']))		{ $_SESSION['item_product5_creditclient_p6']	= $_POST['item_product5_creditclient_p6']; }		else {    $_SESSION['item_product5_creditclient_p6'] = 'non' ; }
if (isset($_POST['item_product5_pdv_p1']))		{ $_SESSION['item_product5_pdv_p1']	= $_POST['item_product5_pdv_p1']; }		else {    $_SESSION['item_product5_pdv_p1'] = 'non' ; }
if (isset($_POST['item_product5_pdv_p2']))		{ $_SESSION['item_product5_pdv_p2']	= $_POST['item_product5_pdv_p2']; }		else {    $_SESSION['item_product5_pdv_p2'] = 'non' ; }
if (isset($_POST['item_product5_pdv_p3']))		{ $_SESSION['item_product5_pdv_p3']	= $_POST['item_product5_pdv_p3']; }		else {    $_SESSION['item_product5_pdv_p3'] = 'non' ; }
if (isset($_POST['item_product5_pdv_p4']))		{ $_SESSION['item_product5_pdv_p4']	= $_POST['item_product5_pdv_p4']; }		else {    $_SESSION['item_product5_pdv_p4'] = 'non' ; }
if (isset($_POST['item_product5_pdv_p5']))		{ $_SESSION['item_product5_pdv_p5']	= $_POST['item_product5_pdv_p5']; }		else {    $_SESSION['item_product5_pdv_p5'] = 'non' ; }
if (isset($_POST['item_product5_pdv_p6']))		{ $_SESSION['item_product5_pdv_p6']	= $_POST['item_product5_pdv_p6']; }		else {    $_SESSION['item_product5_pdv_p6'] = 'non' ; }



?>

